### ISSUE TITLE
Should Code Table D-1: Nil reasons be used?

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/iwxxm#97] opened 2018-07-06 09:00 UTC

**Comment by jkorosi** [comment] 2018-07-06 09:05
I would like to ask if the set of values defined in http://codes.wmo.int/common/nil table should be used for all nil reasons, e.g. all the examples for failed translation are using `<iwxxm:phenomenon nilReason="missing"/>`. Should it be `<iwxxm:phenomenon nilReason="http://www.opengis.net/def/nil/OGC/0/missing"/>` instead? I think this issue is related to Added iwxxm-collect-codelists.sch with codelist Schematron rules #64.

**Comment by blchoy** [comment] 2018-07-09 03:03
Good point.  I think that could be a target but it is obvious that those items under http://codes.wmo.int/common/nil right now is not enough for current use.  Perhaps @marqh could shed some lights on possible future incorporation of IWXXM nilReason descriptions into the WMO Codes Registry?

**Comment by blchoy** [comment] 2018-07-27 20:51
I have changed the examples to use `nilReason="http://codes.wmo.int/common/nil/missing"` instead of just `"missing"`.  The interesting thing is while the former is resolvable, the downloaded RDF file contains only references to `"http://www.opengis.net/def/nil/OGC/0/missing"` instead.  The following is a section of the RDF file concerned:

`    <skos:member>
      <skos:Concept rdf:about="http://www.opengis.net/def/nil/OGC/0/missing">
        <dct:description xml:lang="en">The correct value is not readily available to the sender of this data. Furthermore, a correct value may not exist.</dct:description>
        <rdfs:label xml:lang="en">Missing</rdfs:label>
        <rdfs:seeAlso rdf:resource="http://www.opengis.net/doc/gml#clause-8.2.3.1"/>
        <dc:source xml:lang="en">ISO 19136:2007 'Geographic information - Geography Markup Language' sub-clause 8.2.3.1</dc:source>
      </skos:Concept>`

The problem is that we cannot use this RDF file to validate the codelist items used (#64 refers).  We need @marqh's advise on this.

**Comment by blchoy** [comment] 2018-08-25 05:37
Summarizing the discussions during the telecon on 24 Aug 2018:
1. The common/nil code list on code registries are preferred for nilReason descriptions
2. codes.wmo.int are preferred over other registries even though individual entry of the code list on codes.wmo.int is a wrapper to an entry of another registry as we have full control of the code list.
3. Extending validation with schematron to cover the common/nil code list will only be done when the associated RDF file has been modified to a suitable format.  There may also be a need to not check nilReason descriptions in extensions.

**Comment by braeckel** [comment] 2018-09-10 15:35
Some extra guidance and/or validation on the nilReasons used would be helpful going forward, but this does not easily fit within the timeline for 3.0RC2.

**Comment by blchoy** [comment] 2018-09-12 01:46
Up to this moment, the entities in http://codes.wmo.int/common/nil is enough for use in IWXXM, and we have already changed the guideline and examples to use the code list in 3.0.0RC2.  I suggest we can close this issue and make another one to follow up on future expansion of the code list and use of the associated RDF file for schematron validation.

**Closed** 2018-09-12 01:49 UTC
